MODEL_MOT:
  MAG_SIZE: [3, 4, 7]
  EMBED_DIM: 128
  ORIENT_DIM: 3
  DEPTH: 8
  NUM_HEADS: 8
  MLP_RATIO: 4
  QKV_BIAS: True
  QKV_SCALE: Null
  DROP_RATE: 0.0
  ATTN_DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  LOSS_FUNC: mse
  AUXILIARY_ENABLE: True
  MAG_NOISE_ENABLE: True
  MAG_NOISE_DIR: Data/MOT/MWMR_S/mag_noise_distribution.pyth
  AUXILIARY_NOISE_ENABLE: True
  AUXILIARY_NOISE_DIR: Data/MOT/MWMR_S/auxiliary_noise_distribution.pyth


SOLVER:
  BASE_LR: 0.001
  COSINE_END_LR: 0.0000001
  OPTIMIZING_METHOD: adamw
  WEIGHT_DECAY: 1e-6
  MAX_EPOCH: 300
  LR_POLICY: cosine

TRAIN:
  ENABLE: True
  DATASET: OrientDataset
  BATCH_SIZE: 128
  CHECKPOINT_PERIOD: 2
  EVAL_PERIOD: 2
  AUTO_RESUME: False

TEST:
  ENABLE: True
  DATASET: OrientDataset
  BATCH_SIZE: 1024

DATA:
  PATH_TO_DATA_DIR: Data/MOT/MWMR_S/

DATA_LOADER:
  NUM_WORKERS: 6
  PIN_MEMORY: True

TENSORBOARD:
  ENABLE: False

GPU_ENABLE: True
RNG_SEED: 0
LOG_PERIOD: 100
OUTPUT_DIR: MagTrackTransformer/results/MWMR_S/MOT/
MODEL_NAME: mot_base
DATA_AUGUMENTATION: False
