MODEL_MCT:
  MAG_SIZE: [3, 4, 7]
  NUM_CALIB: 12
  EMBED_DIM: 128
  DEPTH: 12
  NUM_HEADS: 8
  MLP_RATIO: 2
  QKV_BIAS: True
  QKV_SCALE: Null
  DROP_RATE: 0.0
  ATTN_DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  LOSS_FUNC: mse

SOLVER:
  BASE_LR: 0.0001
  COSINE_END_LR: 0.0000001
  OPTIMIZING_METHOD: adamw
  WEIGHT_DECAY: 1e-5
  MAX_EPOCH: 100
  LR_POLICY: cosine

TRAIN:
  ENABLE: True
  DATASET: CalibDataset
  BATCH_SIZE: 128
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 1
  AUTO_RESUME: False
  FINETUNE: True
  CHECKPOINT_FILE_PATH: MagTrackTransformer/trained_NNs/pretrained_MCT/checkpoint_epoch_00140.pyth

TEST:
  ENABLE: True
  DATASET: CalibDataset
  BATCH_SIZE: 1024

DATA:
  PATH_TO_DATA_DIR: Data/MCT_finetune/MWMR_S/calib_mtt_train_1/

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

TENSORBOARD:
  ENABLE: False

GPU_ENABLE: True
RNG_SEED: 0
LOG_PERIOD: 50
OUTPUT_DIR: MagTrackTransformer/results/MWMR_S/calib_mtt_train_1
MODEL_NAME: mct_base


