MODEL_MDT:
  TSUS_SIZE: (3,2,4,7)
  CSUS_SIZE: (3,2,12)
  AUXILIARY_DIM: 3
  EMBED_DIM: 128
  DEPTH: 8
  NUM_HEADS: 8
  MLP_RATIO: 2
  QKV_BIAS: True
  QKV_SCALE: Null
  DROP_RATE: 0.0
  ATTN_DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  NOISE_FREE_RATIO: 0.1
  LOSS_FUNC: mse
  POST_CALIB_NOISE_DIR: Data/magnetic_noise.pyth
  AUXILIARY_ENABLE: False


SOLVER:
  BASE_LR: 0.0001
  COSINE_END_LR: 0.0000001
  OPTIMIZING_METHOD: adamw
  WEIGHT_DECAY: 1e-6
  MAX_EPOCH: 50
  LR_POLICY: cosine

TRAIN:
  ENABLE: True
  DATASET: MDTDataset
  BATCH_SIZE: 128
  CHECKPOINT_PERIOD: 2
  EVAL_PERIOD: 2
  AUTO_RESUME: False

TEST:
  ENABLE: True
  DATASET: MDTDataset
  BATCH_SIZE: 1024
  
DATA:
  PATH_TO_DATA_DIR: Data/MTT/MWMR_S/

DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True

TENSORBOARD:
  ENABLE: False

GPU_ENABLE: True
RNG_SEED: 0
LOG_PERIOD: 100
MODEL_NAME: mdt_base
DATA_AUGUMENTATION: False
OUTPUT_DIR: MagTrackTransformer/results/MWMR_S/MDT/
