MODEL_MTT:
  MAG_SIZE: [3, 32, 4, 7]
  PATCH_SIZE: [4, 2, 3]
  STRIDE_SIZE: [4, 2, 2]
  EMBED_DIM: 128
  DEPTH: 10
  NUM_HEADS: 8
  MLP_RATIO: 4
  QKV_BIAS: True
  QKV_SCALE: Null
  DROP_RATE: 0.0
  ATTN_DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  LOSS_FUNC: mse
  ATTN_TYPE: divided_space_time

SOLVER:
  BASE_LR: 0.0001
  COSINE_END_LR: 0.0000001
  OPTIMIZING_METHOD: adamw
  WEIGHT_DECAY: 1e-5
  MAX_EPOCH: 50
  LR_POLICY: cosine

TRAIN:
  ENABLE: False
  DATASET: TrackingNoiseDataset
  BATCH_SIZE: 128
  CHECKPOINT_PERIOD: 2
  EVAL_PERIOD: 2
  AUTO_RESUME: False
  FINETUNE: True

TEST:
  ENABLE: True
  DATASET: TrackingNoiseDataset
  BATCH_SIZE: 1024

DATA:
  PATH_TO_DATA_DIR: Data/MTT_denoised/MWMR_S/

DATA_LOADER:
  NUM_WORKERS: 6
  PIN_MEMORY: True

TENSORBOARD:
  ENABLE: False

GPU_ENABLE: True
RNG_SEED: 0
LOG_PERIOD: 100
OUTPUT_DIR: MagTrackTransformer/results/MWMR_S/tracking_divide_128_10_4_0.1
MODEL_NAME: mtt_base
DATA_AUGUMENTATION: False

